### ISSUE TITLE
No support for UTF-8 files

### ISSUE THREAD

**Issue by set-soft** [joh/xmldiffs#2]
If an attribute is assigned an UTF-8 value: 

`<?xml version="1.0" encoding="UTF-8"?>
<KPhotoAlbum version="4" compressed="0">
        <image file="Canción">
        </image>
</KPhotoAlbum>`

Python fails:

python /tmp/xmldiffs.py test.xml test.xml 
Traceback (most recent call last):
  File "/tmp/xmldiffs.py", line 97, in <module>
    xmldiffs(file1, file2, diffargs)
  File "/tmp/xmldiffs.py", line 63, in xmldiffs
    write_sorted(tmp1, tree.getroot())
  File "/tmp/xmldiffs.py", line 43, in write_sorted
    children.sort(key=node_key)
  File "/tmp/xmldiffs.py", line 32, in node_key
    return node_str(n)
  File "/tmp/xmldiffs.py", line 25, in node_str
    astr = " ".join(attr_str(k,v) for k,v in attrs)
  File "/tmp/xmldiffs.py", line 25, in <genexpr>
    astr = " ".join(attr_str(k,v) for k,v in attrs)
  File "/tmp/xmldiffs.py", line 21, in attr_str
    return "{}=\"{}\"".format(k,v)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 5: ordinal not in range(128)

Note that the XML file states the encoding is UTF-8. I know Python needs some clues about the encoding, but I don't know where is the best place to configure it. Also note my system *is* UTF-8 encoded: LANG="es_AR.UTF-8"

Here is the above mentioned test file:

[test.xml.txt](https://github.com/joh/xmldiffs/files/890289/test.xml.txt)

**Comment by joh** [comment]
Thanks for reporting this. Seems to be a problem with Python 2 only. Should be fixed now :)
